# Generated by Django 6.0.3 on 2026-04-04 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Слово слишком короткое')], verbose_name='Слово на английском')),
                ('translation', models.CharField(max_length=100, verbose_name='Перевод')),
                ('transcription', models.CharField(blank=True, max_length=100, verbose_name='Транскрипция')),
                ('example_sentence', models.TextField(blank=True, verbose_name='Пример предложения')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10, verbose_name='Уровень сложности')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['-created_at'],
            },
        ),
    ]
